spring:
  application:
    name: cache
  datasource:
    url: jdbc:postgresql://127.0.0.1:5434/users
    username: postgres
    password: start123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
      password: password